# -*- coding: utf-8 -*-
"""Task 3 Basic Chatbot

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1u86pnHZ2n1Oeqvd3rYfoVg6v471bVZ4M
"""

#Project: Task:3 basic Chatbot
#Author: Fozia Roshan

print("========================================================")
print("============== TASK : 3 BASIC CHATBOT ==================")
print("=======================================================")

""" Goal:
Build a simple rule-based chatbot with greetings, jokes, and quotes.

Key Concepts:
if-elif, functions, loops, random, datetime, input/output
"""

import random
from datetime import datetime

def chatbot():
    print("ChatBot: Salam! I'm your friendly Python ChatBot. Type 'bye' to end the chat.\n")

    # Some predefined data
    quotes = [
        " Believe in yourself and you’re halfway there!",
        " Keep going, you’re doing great!",
        " Every day is a new chance to grow.",
        " Hard work always pays off!"
    ]

    jokes = [
        " Why don’t programmers like nature? It has too many bugs!",
        " Why do Python programmers wear glasses? Because they can’t C!",
        " Debugging: being the detective in a crime you committed yourself!"
    ]

    while True:
        user_input = input("You: ").lower()

        # Greeting based on time
        hour = datetime.now().hour
        if "time" in user_input:
            print(f" ChatBot: It's {datetime.now().strftime('%I:%M %p')} right now.")
        elif any(word in user_input for word in ["hi", "hello", "hey", "salam", "assalamualaikum"]):
            if hour < 12:
                print(" ChatBot: Good Morning!  How are you today?")
            elif 12 <= hour < 17:
                print(" ChatBot: Good Afternoon!  Hope your day is going well.")
            else:
                print(" ChatBot: Good Evening!  How was your day?")
        elif user_input in ["i am fine", "fine", "good", "i am good", "alhamdulillah"]:
            print(" ChatBot: Alhamdulillah! That makes me happy ")
        elif "how are you" in user_input:
            print(" ChatBot: I'm always fine when chatting with you ")
        elif "your name" in user_input:
            print(" ChatBot: I'm PyBot — your virtual friend built with Python 💻")
        elif "quote" in user_input or "motivate" in user_input:
            print(" ChatBot:", random.choice(quotes))
        elif "joke" in user_input or "funny" in user_input:
            print(" ChatBot:", random.choice(jokes))
        elif "thank" in user_input:
            print(" ChatBot: You're most welcome ")
        elif "help" in user_input:
            print(" ChatBot: You can ask me about time, quotes, jokes, or just say hello ")
        elif user_input in ["bye", "exit", "quit"]:
            print(" ChatBot: Goodbye! Take care and keep smiling ")
            break
        else:
            print(" ChatBot: Sorry, I didn’t understand that. Try saying 'help' ")

# Run chatbot
chatbot()